name: zoom_sdk
description: Zoom SDK Flutter
version: 0.0.1
repository: https://github.com/infinitly/zoom-sdk-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: net.metainnovative
        pluginClass: ZoomSdk
      ios:
        pluginClass: ZoomSdk
      web:
        pluginClass: ZoomSdkWeb
        fileName: zoom_sdk_web.dart
